name: 'Setup Manticoresearch'
description: 'Setup a Manticoresearch Instance'
author: 'Gordon Anderson'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/_/postgres for supported versions
  # and further details on input environment variables
  manticoresearch version:
    description: 'Version of Manticoresearch to use'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'Dockerfile'
